name: petitparser
version: 4.0.0-nullsafety.1

homepage: https://github.com/petitparser/dart-petitparser
description: A dynamic parser framework to build efficient grammars and parsers
  quickly.

environment:
  sdk: '>=2.12.0-0 <3.0.0'
dependencies:
  characters: ^1.1.0-nullsafety
  meta: ^1.3.0-nullsafety
dev_dependencies:
  test: ^1.16.0-nullsafety
