name: petitparser_examples
version: 4.3.0

homepage: https://github.com/petitparser/dart-petitparser
description: A collection of example parsers, applications, and benchmarks that
  illustrate the PetitParser framework.

environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies:
  collection: ^1.15.0
  meta: ^1.7.0
  more: ^3.2.0
  petitparser: ^4.3.0
dependency_overrides:
  petitparser:
    path: ../petitparser
dev_dependencies:
  build_runner: ^2.1.0
  build_web_compilers: ^3.0.0
  test: ^1.17.0
